"""
probe_terac_webhook.py — get a value into TERAC_WEBHOOK_SECRET.

The secret is generated by Terac, not chosen by us, so it cannot be typed from the dashboard.
The create response is the only place it appears in a create, but
`GET /hooks/subscriptions/{id}/secret` reads it back in full, so a subscription registered by
hand in the dashboard is recoverable too.
docs: https://terac.com/docs/developers/guides/webhooks

    make probe SVC=terac_webhook                                  # list what exists
    make probe SVC=terac_webhook ARGS="--target https://x/hooks/terac"   # register + confirm + read

Read-only without --target. With --target it creates a subscription, which is idempotent: a
second POST for a URL already registered returns 409 naming the existing one, and this treats
that as success and reads the existing secret rather than rotating it.
"""

import argparse
import asyncio
import sys

# Imports app.config purely so .env is loaded the same way the app loads it.
from app.clients.terac import TeracClient, TeracError
from app.config import settings

# Only `submission.approved`. A submission emits roughly five status changes, so also taking
# `submission.status.change` means every approval arrives twice with a different X-Event-ID.
EVENT_TYPES = ["submission.approved"]


def _check_target(url: str) -> None:
    """Terac confirms by POSTing to this URL, so it refuses anything it cannot reach."""
    if not url.startswith("https://"):
        sys.exit(
            f"target_url must be https, got {url!r}.\n"
            "Terac refuses private, loopback, link-local and internal addresses because\n"
            "confirming makes it issue a real request. A localhost PUBLIC_BASE_URL cannot be\n"
            "registered at all — use a tunnel or the deployed host."
        )


async def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--target",
        help="Public https receiver URL. Omit to only list existing subscriptions.",
    )
    args = ap.parse_args()

    async with TeracClient() as terac:
        print("── event types Terac offers ─────────────────────────────────")
        try:
            for row in await terac.list_event_types():
                print("   ", row.get("name") or row.get("event_type") or row)
        except TeracError as exc:
            print(f"    could not read: {exc}")

        print("\n── subscriptions that already exist ────────────────────────")
        existing = await terac._request("GET", "/hooks/subscriptions")
        rows = existing.get("data") or []
        if not rows:
            print("    (none)")
        for row in rows:
            print(f"    {row.get('id')}  ->  {row.get('target_url')}")
            print(f"        events={row.get('event_types')}")
            print(
                f"        enabled={row.get('is_enabled')} confirmed_at={row.get('confirmed_at')}"
                f" disabled_reason={row.get('disabled_reason')}"
            )
            if not row.get("confirmed_at"):
                print("        ^ UNCONFIRMED — receives nothing until confirmed.")

        if not args.target:
            print(
                "\nNo --target given, so nothing was changed. Pass one to register and read the"
                "\nsecret. Current PUBLIC_BASE_URL would make the receiver:"
                f"\n    {settings.public_base_url}/hooks/terac"
            )
            return

        _check_target(args.target)

        print(f"\n── registering {args.target} ───────────────────────────────")
        result = await terac.ensure_webhook(args.target)
        subscription_id = result.get("id")
        print(f"    id={subscription_id} confirmed={result.get('confirmed')}")
        if result.get("confirmed") is False:
            print(
                "    Confirmation failed: your receiver did not answer 2xx to the ping.\n"
                "    Is the server running and publicly reachable at that URL?"
            )

        if not subscription_id:
            print("    No subscription id came back, so there is no secret to read.")
            return

        secret = (await terac.get_webhook_secret(str(subscription_id))).get("secret")
        if not secret:
            print("    Secret not present in the response; read it from the dashboard.")
            return

        print("\n── put this in .env ────────────────────────────────────────")
        print(f"TERAC_WEBHOOK_SECRET={secret}")
        if settings.terac_webhook_secret and settings.terac_webhook_secret != secret:
            print(
                "\n    NOTE: TERAC_WEBHOOK_SECRET is already set to a DIFFERENT value. Every\n"
                "    delivery is failing signature verification right now. Replace it."
            )


if __name__ == "__main__":
    asyncio.run(main())
